### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by Ayfri** [Cohelion/CS.Changelog#1]
Hi, I'm trying to use this tool to generate a changelog from my `v3` branch that is ahead the `master` branch, but I don't understand how 🤔

**Comment by Atrejoe** [comment]
My apologies for not responding sooner.

In general this tool adheres to gitflow: execute on the branch you want tyo report the changes for (usually this is `release/v3`) in your case.

Any feature or hotfix branch merged into your current branch will be listed.
Also commit with explicit changelog messages will be included:

> Commit messages with a category prefix will always be included, like
>>`[Feature] Human-friendly of my beautiful feature`
>>`[Hotfix] Description of the thing that was fixed (and tested)`
>>`[Cosmetics] ABC-42 A shiny new button has been added`

These changes will be written to `changelog.json` (by default), but can also be written to markdown or html.

# Install the tool:
Given that you have .Net core installed, run:

```
dotnet tool install --global cs.changelog.console
```

Or download the binaries from [../releases](../releases)

In your case, taking your repo https://github.com/Ayfri/discord-fetch-messages for instance:

Running the initial creation of the changelog, creating a markdownfile:

`changelog --full -o MarkDown`
incremental updates (from the last tag) can be done using:
`changelog -o MarkDown`

This results in:

![image](https://user-images.githubusercontent.com/585091/132511000-45f3341f-f454-4f41-b3fc-4ac342db02e2.png)

Which is not very helpful. If you adhere to the branching conventions and/or commit message conventions, this wóuld result in a helpful format.

for more options and output formats, see:

`changelog --help`or [../ReadMe.md](../blob/develop/ReadMe.md)

**Comment by Atrejoe** [comment]
If you provide the repo you want to prepare a changelog for, I'll provide a more concrete example.
